apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: nginx
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/<your-username>/<repository-name>
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: nginx
  namespace: flux-system
spec:
  interval: 1m
  path: ./apps/nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: nginx
  targetNamespace: default
